### ISSUE TITLE
Unable to disassemble - lzma Issue

### ISSUE THREAD

**Issue by Jademalo** [op1hacks/op1repacker#18]
```
op1repacker unpack op1_225.op1
Traceback (most recent call last):
  File "/usr/local/bin/op1repacker", line 11, in <module>
    load_entry_point('op1repacker==0.1.4', 'console_scripts', 'op1repacker')()
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.5/site-packages/op1repacker/main.py", line 10, in <module>
    from . import op_repack
  File "/usr/local/lib/python3.5/site-packages/op1repacker/op_repack.py", line 6, in <module>
    import lzma
  File "/usr/local/lib/python3.5/lzma.py", line 26, in <module>
    from _lzma import *
ImportError: No module named '_lzma'
```
```
sudo pip3 install pyliblzma
Collecting pyliblzma
  Using cached pyliblzma-0.5.3.tar.bz2
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-drekpzhs/pyliblzma/setup.py", line 40, in <module>
        for i in xrange(len(c_files)):
    NameError: name 'xrange' is not defined

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-drekpzhs/pyliblzma/
```

No idea what to do from here, I just can't get python3 to recognise lzma. After a bit of research someone mentioned that it might be that liblzma-dev is required, but when trying to install that I get this;

```
sudo apt-get install liblzma-dev               Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 liblzma-dev : Depends: liblzma5 (= 5.1.1alpha+20120614-2+b3) but 5.2.2-1.2 is to be installed
E: Unable to correct problems, you have held broken packages.
```

So yeah, now I'm stuck. Can't get it to run at all. No idea where to go from here. Any advice?

**Comment by Jademalo** [comment]
Debian Jessie, nothing particularly special about it. Did an apt upgrade immediately before trying to install this.

**Comment by richrd** [comment]
I'm not quite sure how to fix that, but I would probably try fixing the package problem first. First I'd try removing liblzma-dev. A more recent version of Python3 might help but it seems like Jessie doesn't ship a newer version. One way might be upgrading your OS from Jessie to Stretch, but I'm not sure whether you're able to do that.

**Comment by Jademalo** [comment]
```
sudo apt-get remove liblzma-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package 'liblzma-dev' is not installed, so not removed
0 upgraded, 0 newly installed, 0 to remove and 10 not upgraded.
```
Welp.
Not really sure what to do now. I could update to stretch, I'll look into that.

Ended up using Windows Python to do this, was able to get it unpacked, repacked, and installed without issue. Would still love to know why it's not working on Debian though.

Thanks

**Comment by richrd** [comment]
I'll close this as it seems to be an OS or Python installation issue.
