### ISSUE TITLE
"analyse" fails on Windows with firmware 242

### ISSUE THREAD

**Issue by jsmonzani** [op1hacks/op1repacker#33]
Here's the error: (Python 3.8.3)

Analyzing c:\sound\op1\firmwares\op1_242-JS...
Traceback (most recent call last):
  File "C:\Users\DELL 6540\AppData\Roaming\Python\Python38\Scripts\op1repacker-script.py", line 11, in <module>
    load_entry_point('op1repacker==0.2.4', 'console_scripts', 'op1repacker')()
  File "C:\Users\DELL 6540\AppData\Roaming\Python\Python38\site-packages\op1repacker\main.py", line 78, in main
    data = op1_analyze.analyze_unpacked_fw(target_path)
  File "C:\Users\DELL 6540\AppData\Roaming\Python\Python38\site-packages\op1repacker\op1_analyze.py", line 74, in analyze_unpacked_fw
    fs_info = analyze_fs(target)
  File "C:\Users\DELL 6540\AppData\Roaming\Python\Python38\site-packages\op1repacker\op1_analyze.py", line 59, in analyze_fs
    mtime = os.path.getmtime(file_path)
  File "c:\apps\python\lib\genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'c:sound\\op1\\firmwares\\op1_242-JS\\OP1_vdk.ldr'

Packing / unpacking works fine, it seems.
Thank you!

**Comment by richrd** [comment]
At the end it says `FileNotFoundError: [WinError 3] The system cannot find the path specified: 'c:sound\op1\firmwares\op1_242-JS\OP1_vdk.ldr'`
Can you check that the file exists? It could be that there's some windows specific path bug in op1repacker that's causing this.

**Comment by jsmonzani** [comment]
Hank @richrd ! Yes, I forgot to mention that OP1_vdk.ldr was there.
 I think I found your problem: look it says:
c:sound\op1\firmwares\op1_242-JS\OP1_vdk.ldr
with c: instead of c:\ 
So there's a \ missing after the drive name :)
Hope this helps

**Comment by richrd** [comment]
Thanks! This should be fixed in version 0.2.5.
